### PR TITLE
Fix geoblacklight wms and iiif references for scanned maps

### LINKED ISSUE #1195: Geoblacklight references are incorrect for scanned maps
Two main issues:

- WMS/WFS references are being generated for scanned maps. This breaks proper display in pulmap.
- IIIF references are generated for restricted scanned maps in some cases.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #1195

### CODE REVIEW

File: app/services/discovery/iiif_builder.rb [hunk 1]
```diff
@@ -40,6 +40,13 @@ def geo_file_set?
         @file_set_ids.include? file_set.id
       end
 
+      # Tests if the file set is a geo_works image format.
+      # @return [Bool]
+      def file_set_format?
```
Comment (escowles) [inline app/services/discovery/iiif_builder.rb]: Maybe roll this into `geo_file_set?` ?

Comment (eliotjordan) [inline app/services/discovery/iiif_builder.rb]: Rolled.
